language: python
python:
  - 3.6
  - 3.7
  - 3.8

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.hypothesis

install:
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install --upgrade pytest
  - pip install coveralls==1.1 hypothesis pytest-cov
script:
  - pytest --cov=src/matching tests
  - pip uninstall -y matching
  - pip install matching
after_success: coveralls

