language: python
python:
  - 3.6

cache:
  directories:
    - $TRAVIS_BUILD_DIR/.hypothesis

install:
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install --upgrade pytest
  - pip install coveralls==1.1 hypothesis pytest-cov
  - pip install sphinx sphinx_rtd_theme
  - pip install nbval
  - pip install pandas  # for testing
script:
    #  - cd docs; make html
    #  - cd ..
    #  - pytest --doctest-glob='.rst'
  - pytest --cov=src/matching tests
  - pytest --nbval --current-env docs/
  - python -m doctest paper.md
  - python -m doctest README.rst
  - pip uninstall -y matching
  - pip install matching
after_success: coveralls

