[project]
name = "matching"
authors = [
    { name="Henry Wilde", email="henrydavidwilde@gmail.com" },
    { name="Vince Knight" },
]
description = "A package for solving matching games"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT Licence"}
keywords = [
    "game-theory",
    "gale-shapley",
    "matching-games",
    "stable-marriage",
    "hospital-resident",
    "stable-roommates",
    "project-allocation",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
dependencies = [
    "numpy>=2.2.4",
    "scipy>=1.11.3",
]
dynamic = ["version"]

[build-system]
requires = ["setuptools>=62"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = [
    "hypothesis>=6.129.4",
    "nbval>=0.11.0",
    "pytest>=7.4.4",
    "pytest-cov>=6.0.0",
    "pytest-randomly>=3.16.0",
]
docs = [
    "ipython>=7.34.0",
    "matplotlib>=3.10.1",
    "nbsphinx>=0.9.7",
    "pandas>=2.2.3",
    "pyyaml>=6.0.1",
    "quartodoc>=0.9.1",
]
dev = [
    "matching[docs,test]",
    "pytest-sugar>=1.0.0",
    "ruff>=0.11.1",
]

[project.urls]
homepage = "https://github.com/daffidwilde/matching"
documentation = "https://daffidwilde.github.io/matching"
changelog = "https://github.com/daffidwilde/matching/blob/main/CHANGES.md"

[tool.setuptools.dynamic]
version = {attr = "matching.__version__"}

[tool.ruff]
line-length = 99
extend-include = ["*.ipynb"]

[tool.ruff.lint]
extend-select = ["D", "DOC", "I", "RUF", "W"]
ignore = ["D105", "D107"]

[tool.ruff.lint.isort]
known-first-party = ["matching"]

[tool.ruff.lint.per-file-ignores]
"docs/*" = ["D100", "D103", "E402"]
"src/matching/base.py" = ["D401"]
"tests/*.py" = ["D104", "D401"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.coverage.run]
branch = true
