project:
  type: website

website:
  title: "matching"
  navbar:
    left:
      - href: tutorials/index.qmd
        text: tutorials
      - href: how-to/index.qmd
        text: how-to guides
      - href: discussion/index.qmd
        text: discussion
      - href: bibliography.qmd
        text: bibliography
    right:
      - icon: github
        href: https://github.com/daffidwilde/matching
      - icon: journal-text
        href: https://doi.org/10.21105/joss.02169
  page-footer:
    left: >
      Copyright, Henry Wilde 2023.
      Powered by [Quarto](https://quarto.org/docs/websites)
      and [Diátaxis](https://diataxis.fr).

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    mainfont: Arial

bibliography: assets/bibliography.bib

toc: true