---
title: Contributing to the library
---

If you are interested in contributing to the `matching` then first
of all we would like to offer our thanks and say welcome!

Whether you're looking to provide a fix for a current
[issue](https://github.com/daffidwilde/matching/issues), report a bug or
implement a new feature to the library, your contributions are always
welcome. Pull requests are a good place to discuss contributions so
please do not feel you must present a perfect product from the off.

## Quick-start

To make a contribution via a pull request, follow these steps:

1.  Go to the [GitHub repository](https://github.com/daffidwilde/matching),
    make a fork, and clone the repo locally:

        $ git clone git@github.com/<your-username>/matching.git

2.  Assuming you have all the dependencies installed, the next step is
    to ensure that all the tests pass (this should not take very long at all):

        $ cd matching
        $ pytest tests

3.  Make your changes and write tests to go with them, ensuring they pass, too.

4.  Push to your fork and open a pull request.

## Best practices

If you're interested in improving your skills as an open-source contributor,
please consider this [extensive guide within the Nashpy documentation](https://nashpy.readthedocs.io/en/stable/contributing/index.html).
They set out some great examples and discussion there, while adhering to the
Diátaxis framework for good documentation.