name: CI
on:
  pull_request:
  push:
    branches:
      - "main"
      - "dev*"

jobs:
  ci:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras

      - name: Run linters (3.13-ubuntu only)
        if: |
          matrix.python-version == '3.13' &&
          matrix.os == 'ubuntu-latest'
        run: |
          uv run ruff format --check .
          uv run ruff check .

      - name: Run documentation tests
        run: |
          uv run python -m doctest README.md
          uv run pytest docs --nbval --nbval-current-env -p no:randomly

      - name: Run unit tests
        run: |
          uv run pytest tests --cov --cov-fail-under=100 --hypothesis-profile=ci
