name: CI
on:
  pull_request:
  push:
    branches:
      - "main"
      - "dev*"

jobs:
  ci:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Update pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[docs,test]"

      - name: Run tests
        run: |
          python -m doctest README.md
          python -m doctest paper.md
          python -m pytest docs --nbval --nbval-current-env -p no:randomly
          python -m pytest tests \
            --cov=matching --cov-fail-under=100 --hypothesis-profile=ci

      - name: Install and run linters (3.11-ubuntu only)
        if: |
          matrix.python-version == '3.11' &&
          matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install ".[lint]"
          python -m ruff check .
          python -m ruff format --check .
